(function(){
'use strict';
const {CAST,buildStory,NOTES,ACTIVITIES,CHAPTER_OUTLINE,voice,activityFeedback,JOURNAL,REV8_NODES,LEGACY_SEGMENTS,PREVIOUS_SEGMENTS,REV5_SEGMENTS}=window.GameContent;
const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const KEY='constitution-afterclass-v1';
const STORIES=Object.fromEntries(Object.keys(CAST).map(k=>[k,buildStory(k)]));
const backgrounds={campus:'assets/campus.webp',room:'assets/reading-room.webp','cg-h':CAST.h.cg,'cg-s':CAST.s.cg,'cg-d':CAST.d.cg,'cg-k':CAST.k.cg};
let migrated=false;
let store={version:1,courseRevision:9,settings:{music:.35,sfx:.25,speed:28,mute:false},save:null,notes:[],journal:[],gallery:[]};
let storageOK=true;try{const old=JSON.parse(localStorage.getItem(KEY)||'null');if(old?.version===1){store.settings={...store.settings,...old.settings};store.notes=old.courseRevision>=3&&Array.isArray(old.notes)?old.notes.filter(n=>[1,2,3].includes(n)):[];store.gallery=Array.isArray(old.gallery)?old.gallery.filter(r=>CAST[r]):[];store.journal=Array.isArray(old.journal)?old.journal.filter(k=>JOURNAL.some(j=>j.key===k)):JOURNAL.filter(j=>store.notes.includes(j.lesson)).map(j=>j.key);const s=old.save;if(s&&old.courseRevision===8&&CAST[s.route]){const previous=REV8_NODES[s.route][s.index];const match=s.completed?STORIES[s.route].length-1:STORIES[s.route].findIndex(n=>previous?.activity?n.activity===previous.activity:(n.anchor||n.text)===previous?.anchor&&n.segment===previous?.segment);s.index=match>=0?match:Math.max(0,STORIES[s.route].findIndex(n=>n.segment===previous?.segment));s.history=[];delete s.exercise;for(const n of STORIES[s.route].slice(0,s.index+1))if(n.record&&!store.journal.includes(n.record))store.journal.push(n.record);}else if(s&&old.courseRevision!==9&&CAST[s.route]){const segment=s.completed?'lesson1':(old.courseRevision>=5?REV5_SEGMENTS:old.courseRevision>=3?PREVIOUS_SEGMENTS:LEGACY_SEGMENTS)[s.route][s.index]||'lesson1';s.index=Math.max(0,STORIES[s.route].findIndex(n=>n.segment===segment));s.history=[];delete s.exercise;s.completed=false;migrated=true}if(s&&CAST[s.route]&&Number.isInteger(s.index)&&s.index>=0&&s.index<STORIES[s.route].length&&typeof s.vars==='object'){store.save={...s,name:String(s.name||'你').slice(0,12),history:Array.isArray(s.history)?s.history.slice(-160):[]}}}}catch(e){storageOK=false}
for(const k of ['music','sfx'])store.settings[k]=Math.max(0,Math.min(1,Number(store.settings[k])||0));
store.settings.speed=[0,18,28,45].includes(store.settings.speed)?store.settings.speed:28;
let mode='title',session=null,typeTimer=null,typing=false,fullText='',toastTimer,clean=false,unlockAudio=false;
let fadeTimer=null,currentTrack='',trackToken=0,deck=null,fadingOld=null,audioError=false;
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(store));storageOK=true}catch(e){storageOK=false}}
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function volume(){return store.settings.mute?0:store.settings.music}
function updateVolume(){if(deck)deck.volume=volume();if(fadingOld&&store.settings.mute)fadingOld.volume=0}
function playTrack(name){
 if(!unlockAudio||!name)return;
 if(name===currentTrack&&deck){if(deck.paused&&!document.hidden)deck.play().catch(()=>{});return}
 const token=++trackToken;clearInterval(fadeTimer);if(fadingOld&&fadingOld!==deck){fadingOld.pause();fadingOld.removeAttribute('src');fadingOld.load()}const old=deck;fadingOld=old;const oldVolume=old?.volume||0;
 currentTrack=name;const next=new Audio('assets/'+name+'.mp3');next.loop=true;next.preload='auto';next.volume=0;deck=next;
 next.addEventListener('error',()=>{audioError=true;toast('配樂暫時無法載入，可在設定重新啟用。')},{once:true});
 next.play().then(()=>{if(token!==trackToken){next.pause();return}audioError=false;let i=0;fadeTimer=setInterval(()=>{i++;let a=Math.min(1,i/28);next.volume=volume()*a;if(old)old.volume=store.settings.mute?0:oldVolume*(1-a);if(a===1){clearInterval(fadeTimer);if(old){old.pause();old.removeAttribute('src');old.load()}}},40)}).catch(()=>{if(old)old.pause();audioError=true});
}
let fxCtx;
function clickSound(){if(!unlockAudio||store.settings.mute||store.settings.sfx===0)return;try{fxCtx=fxCtx||new(window.AudioContext||window.webkitAudioContext)();if(fxCtx.state==='suspended')fxCtx.resume();let o=fxCtx.createOscillator(),g=fxCtx.createGain();o.type='sine';o.frequency.setValueAtTime(820,fxCtx.currentTime);o.frequency.exponentialRampToValueAtTime(510,fxCtx.currentTime+.07);g.gain.setValueAtTime(.013*store.settings.sfx,fxCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,fxCtx.currentTime+.08);o.connect(g);g.connect(fxCtx.destination);o.start();o.stop(fxCtx.currentTime+.09)}catch(e){}}
function activate(){unlockAudio=true;clickSound()}
function nav(withHome=true){return `<div class="nav">${withHome?'<button class="glass-btn" data-action="home" aria-label="返回標題">返回</button>':''}<button class="glass-btn" data-action="notes">筆記</button><button class="glass-btn" data-action="settings" aria-label="設定與音量">設定</button></div>`}
function sceneClass(extra,bg){return `class="scene ${extra}" style="--bg:url('${bg}')"`}
function title(){mode='title';stopTyping();session=null;clean=false;if(unlockAudio)playTrack('campus');app.innerHTML=`<section ${sceneClass('start pet-cover',backgrounds.campus)}><header class="topbar"><div class="brand-small">晴川大學</div>${nav(false)}</header><div class="start-content"><div class="chapter-label">第一章 · 靠窗的位置</div><h1>憲法<br>放課後</h1><div class="title-en">AFTER CLASS, WITH YOU</div><p class="start-copy">這週的讀書會，要來嗎？<br>學長、學姐，還有會講話的校狗和校貓。</p><div class="start-actions"><button class="primary" data-action="choose">開始新的故事</button>${store.save?'<button class="secondary" data-action="resume">繼續上次</button>':''}</div></div><div class="start-cast" aria-hidden="true"><img src="${CAST.d.portrait}" alt=""><img src="${CAST.k.portrait}" alt=""></div><div class="start-foot">建議開啟聲音 · 點擊對話前進 · 自動記錄進度</div></section>`;}
function choose(){mode='choose';activate();playTrack('campus');app.innerHTML=`<section ${sceneClass('choose',backgrounds.campus)}><header class="topbar"><div class="brand-small">憲法放課後</div>${nav()}</header><div class="choose-heading"><div><div class="eyebrow">FIRST WEEK</div><h2>想和誰一起讀？</h2></div><label class="name-field">你的名字 <input id="player-name" maxlength="12" value="${esc(store.save?.name==='你'?'':store.save?.name||'')}" placeholder="可留空" autocomplete="off"></label></div><div class="cast-grid">${Object.entries(CAST).map(([k,c])=>`<button class="cast-card ${['d','k'].includes(k)?'dog':''}" data-route="${k}" aria-label="選擇${c.name}"><img src="${c.portrait}" alt="${c.name}的角色立繪"><span class="cast-info"><span class="role">${c.role}</span><strong>${c.name}</strong><span class="desc">${c.tag}</span><span class="enter">${c.quote}</span></span></button>`).join('')}</div></section>`;}
function newGame(route){const name=($('#player-name')?.value.trim()||'你').slice(0,12);session={route,index:0,name,vars:{drink:'水',dogDay:'walk'},history:[],completed:false};mode='game';activate();renderNode();}
function resume(){if(!store.save)return choose();session=structuredClone(store.save);mode='game';activate();renderNode();if(migrated){toast('課程已擴充，從本節重新開始；相處紀錄與相簿已保留。');migrated=false}}
function stopTyping(){clearInterval(typeTimer);typing=false}
function fillText(text){stopTyping();fullText=text;const el=$('.dialogue-text');if(!el)return;const speed=store.settings.speed;if(speed===0||window.matchMedia('(prefers-reduced-motion: reduce)').matches){el.textContent=text;return}let i=0;typing=true;const chars=Array.from(text);el.textContent='';typeTimer=setInterval(()=>{i+=2;el.textContent=chars.slice(0,i).join('');if(i>=chars.length)stopTyping()},speed)}
function finishTyping(){stopTyping();const el=$('.dialogue-text');if(el)el.textContent=fullText}
function interpolate(text){const v=session.vars,drink=v.drink||'水';return String(text||'').replace(/\{(\w+)\}/g,(_,key)=>({
 drinkH:drink==='水'?'對了，飲水機在那邊。我剛剛才去裝過。':`剛剛買了${drink}，幫你帶一杯。`,
 drinkS:drink==='水'?'我下次也帶水好了。飲料錢有夠多。':`你喝${drink}對吧？下次我買。`,
 dogRecall:v.dogDay==='sit'?'要去那張長椅嗎？':'要不要走上次那條路？',
 dogReply:v.dogDay==='sit'?'好，你上次坐的那邊還沒人。':'好啊。今天走慢一點，我剛吃飽。'
 }[key]||''))}
function studyImage(id){return 'assets/study-'+id+'.webp'+(id.startsWith('d-')?'?v=7':'')}
function current(){return session?STORIES[session.route][session.index]:null}
function save(){if(!session)return;store.save=structuredClone(session);persist()}
function renderNode(){
 if(!session)return;stopTyping();mode='game';clean=false;const nodes=STORIES[session.route];let count=0;while(nodes[session.index]?.kind==='skip'){session.index=nodes[session.index].next;if(++count>30)throw Error('故事流程錯誤')}
 const n=current();if(!n)return end();if(n.kind==='end')return end();
 if(n.record&&!store.journal.includes(n.record)){store.journal.push(n.record);toast('筆記已補上：'+JOURNAL.find(j=>j.key===n.record).title)}if(n.effect)Object.assign(session.vars,n.effect);if(n.learn&&!store.notes.includes(n.learn)){store.notes.push(n.learn);toast('已收進筆記：'+NOTES[n.learn-1].title)}
 if(n.unlock&&!store.gallery.includes(n.unlock)){store.gallery.push(n.unlock);toast('新的回憶已收藏')}
 if(n.kind==='activity')exerciseState();
 const text=n.kind==='activity'?exerciseText():interpolate(n.text),speaker=n.who==='你'?session.name:n.who;
 const historyId=n.kind==='activity'?'activity-'+n.id+'-'+session.exercise.step:n.id;if((n.kind!=='activity'||!session.exercise.feedback)&&session.history.at(-1)?.id!==historyId)session.history.push({id:historyId,who:speaker,text});session.history=session.history.slice(-160);save();
 playTrack(n.music);const c=CAST[n.cast||session.route],isDog=['d','k'].includes(n.cast||session.route);
 const previousArt=app.querySelector('.study-art picture'),previousPortrait=app.querySelector('.portrait');
 app.innerHTML=`<section ${sceneClass(`game ${n.study?'study-scene':''} ${n.diagram||n.kind==='activity'?'has-teaching':''} ${n.kind==='activity'?'activity-scene':''} ${n.event?'event':''} ${['cg-d','cg-k'].includes(n.bg)?'dog-event':''}`,backgrounds[n.bg])}><header class="topbar"><div class="pill"><strong>${n.day}</strong><span class="day-detail">${n.place}</span></div>${nav()}</header><div class="game-main">${n.study?`<div class="study-art"><picture>${n.study.endsWith('-c')&&session.route!=='k'?`<source media="(max-width:760px) and (max-height:650px)" srcset="${studyImage(session.route+'-a')}">`:''}<img src="${studyImage(n.study)}" alt="${c.name}${n.study.endsWith('a')?'一起翻書講解':'陪你思考的上課插畫'}"></picture><button class="glass-btn study-view" data-action="studyart">欣賞圖片</button></div>`:''}${n.chapter?`<div class="chapter-card"><div class="eyebrow">${n.day} AFTER CLASS</div><div class="day-title">${esc(n.chapter.split(' · ').at(-1))}</div><p>${n.lesson?'今天就從這裡開始。':'你的第一週，從這裡開始。'}</p></div>`:''}${n.portrait?`<img class="portrait ${isDog?'dog':''}" src="${c.portrait}" alt="${c.name}">`:''}${n.kind==='activity'?exercisePanel():''}${n.diagram?`<div class="lesson-panel"><div class="lesson-top"><h2>${diagramTitle(n.diagram)}</h2><button class="diagram-expand" data-action="diagram">放大</button><span class="step-label">${n.lesson?`第一章・第${n.lesson}節`:'第一週'}</span></div><div class="teaching">${diagram(n.diagram,n.stage)}</div></div>`:''}</div>${n.event?'<button class="glass-btn cg-view" data-action="viewcg">欣賞圖片</button>':''}<div class="reading-deck"><div class="dialogue"><div class="speaker ${n.who==='你'?'player':!n.who?'narrator':''}">${esc(speaker||'放課後')}</div><div class="dialogue-text" aria-live="polite"></div><div class="dialogue-footer"><span><span class="scene-progress"><i style="width:${Math.min(100,(session.index/nodes.length)*100)}%"></i></span>${storageOK?'<span class="save-dot"></span>已記錄':'本次進度暫未保存'}</span><div><button class="next-btn" data-action="history">回看</button>${n.kind==='activity'?exerciseFooter():n.kind==='choice'?'<span class="muted">請選擇回應</span>':'<button class="next-btn" data-action="next">繼續 ▸</button>'}</div></div></div>${n.kind==='choice'?`<div class="choices" aria-label="選擇你的回應">${n.options.map((o,i)=>`<button class="choice-btn" data-option="${i}"><span>0${i+1}</span>${esc(o.label)}</button>`).join('')}</div>`:''}</div></section>`;
 const nextArt=app.querySelector('.study-art picture'),nextPortrait=app.querySelector('.portrait');
 if(previousArt&&nextArt&&previousArt.innerHTML===nextArt.innerHTML)nextArt.replaceWith(previousArt);
 if(previousPortrait&&nextPortrait&&previousPortrait.getAttribute('src')===nextPortrait.getAttribute('src'))nextPortrait.replaceWith(previousPortrait);
 if(n.kind==='choice'||n.kind==='activity'){$('.dialogue-text').textContent=text;fullText=text}else fillText(text);
}
function next(){if(mode!=='game'||modal.open)return;if(typing){finishTyping();return}const n=current();if(!n||n.kind==='choice')return;if(n.kind==='activity')return exerciseContinue();session.index=n.next;renderNode()}
function option(index){const n=current();if(mode!=='game'||n?.kind!=='choice'||!Number.isInteger(index)||!n.options[index])throw Error('目前沒有這個選項');const o=n.options[index];Object.assign(session.vars,o.set);session.history.push({id:'choice-'+n.id,who:session.name,text:o.label});session.index=o.target;clickSound();renderNode()}
function end(){stopTyping();session.completed=true;session.index=STORIES[session.route].length-1;save();mode='end';const c=CAST[session.route];playTrack('tender');app.innerHTML=`<section ${sceneClass('end',backgrounds.room)}><header class="topbar"><div class="brand-small">憲法放課後</div>${nav()}</header><div class="end-card"><div class="eyebrow">第一章結束 · ${c.name}</div><h2>${c.end}</h2><img class="end-image" src="${c.cg}" alt="${c.end}的事件圖片"><p class="end-line">${c.ending}</p><div class="end-actions"><button class="primary" data-action="notes">翻開這週的筆記</button><button class="secondary" data-action="gallery">回憶相簿</button><button class="secondary" data-action="choose">另一段相遇</button></div><p class="muted" style="margin-top:20px">第一週的故事已完成。下次，再一起讀。</p></div></section>`;}
function diagramTitle(type){return {'change-terms':'變遷：先看用詞範圍','custom-461':'461號：兩種列席情境',residence:'最大效力：居住自由','amend-forms':'修憲形式與憲法破棄',constituted:'制憲權與被制定權','review-path':'先確定可以審查',charter:'界限說的理論區分',origin:'為什麼只換人還不夠',functions:'權力與權利',foundation:'憲法的基本概念',system:'憲法的規範體系',reading:'怎麼讀懂憲法',change:'憲法的變遷與成長',custom:'憲政慣例',interpret:'憲法解釋',amendment:'憲法修改',limits:'修憲的界限'}[type]||''}
function icon(type){const paths={building:'<path d="M8 22 32 8l24 14H8Zm5 4v24m13-24v24m12-24v24m13-24v24M7 54h50"/>',book:'<path d="M8 12h15q9 0 9 7q0-7 9-7h15v40H41q-9 0-9 5q0-5-9-5H8V12Zm24 7v34M15 23h9m-9 9h9m16-9h9m-9 9h9"/>',person:'<circle cx="32" cy="17" r="9"/><path d="M14 55V43q0-15 18-15t18 15v12M23 43v12m18-12v12"/>',phone:'<rect x="19" y="5" width="27" height="54" rx="5"/><path d="M26 13h13M29 51h7M8 22l-5 5 5 5m-4-5h10"/>',search:'<circle cx="27" cy="26" r="17"/><path d="m40 39 17 17M19 26h16m-8-8v16"/>',amend:'<path d="M10 7h32v49H10V7Zm9 12h15m-15 9h15m-15 9h8M35 47l16-16 7 7-16 16-10 3 3-10Z"/>'};return `<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[type]||paths.book}</svg>`}
function diagram(type,stage){
 const cards=(items,active=-1)=>`<div class="concept-grid ${items.length>2?'overview':''} ${active>=0?'has-focus':''}">${items.map(([title,detail],i)=>`<div class="concept-card ${active===i?'focused':''}"><strong>${title}</strong><span>${detail}</span></div>`).join('')}</div>`;
 if(type==='change-terms')return `<div class="scope-map"><div><strong>廣義變遷</strong><p>慣例・解釋・修改</p></div><div><strong>狹義變遷</strong><p>不修改條文的調適</p></div></div>`;
 if(type==='custom-461')return cards(stage===1?[['立法院會議','依第71條列席陳述意見'],['司法・考試・監察院長','得列席']]:[['立法院委員會','依第67條第2項邀請備詢'],['三院院長','依循慣例，得不受邀請備詢']]);
 if(type==='residence')return `<div class="scope-map residence-map"><strong>居住自由的保障範圍</strong><div><span>住宅</span>${stage>=2?'<span>營業場所</span><span>辦公處所</span>':''}</div><p>${stage>=2?'最大效力：不只限於住宅':'先辨認保障範圍'}</p></div>`;
 if(type==='amend-forms')return stage===1?`<div class="document-compare"><div><strong>直接增刪</strong><p>原條文 → 修改後條文</p><small>德國基本法的方式</small></div><div><strong>另外增補</strong><p>本文 ＋ 增補條文</p><small>美國方式；我國自1991年採用</small></div></div>`:`<div class="document-compare exceptional"><strong>憲法之外的特別規定</strong><p>以修憲特別多數制定 → 排斥部分憲法規定</p><small>憲法破棄：損及最高性，原則不容許</small></div>`;
 if(type==='constituted')return `<div class="power-map"><div><strong>制憲權</strong><small>創設憲法秩序</small></div><span>↓</span><div><strong>憲法</strong><small>建立並限制國家權力</small></div><span>↓</span><div><strong>修憲權等被制定權</strong><small>肯定說：不能推翻基本決定</small></div></div>`;
 if(type==='review-path')return `<ol class="review-path"><li>先說明修憲可以被審查<span>釋字第499號：修憲有界限</span></li>${stage>=2?'<li>再檢查是否侵害基本原則<span>接著進行實質討論</span></li>':''}</ol>`;
 if(type==='charter')return cards([['憲章','涉及憲法基本決定 → 不得修改'],['憲律','不涉及基本決定 → 得修改']])+`<p class="diagram-caption">界限說的理論區分；無界限說質疑其依據</p>`;
 if(type==='origin')return `<div class="book-story">${icon('building')}<strong>國王掌握權力</strong><div class="rights-row"><span>訂規則</span><span>執行</span><span>處罰</span></div><div class="flow-arrow">↓</div><p>${stage===1?'權力集中在同一個人身上':'先約定組織、權限與限制'}</p>${stage>=2?'<div class="flow-arrow">↓</div><strong class="diagram-pill">用根本大法拘束權力</strong>':''}<small>假設的國王故事</small></div>`;
 if(type==='functions')return cards([['國家組織與權限','權力交給誰？如何限制？'],['人民基本權利','國家行使權力時，必須顧及保障']]);
 if(type==='foundation')return cards([['國家的框架','制憲者對國家樣貌的想像'],['最高性','法律體系的根源與效力來源'],['人民授權','連結民主與法治'],['限制與保障','規範國家權力、保障人民權利']]);
 if(type==='system')return cards([['前言與總綱','憲法前言／基本原則／國民與領土'],['人民權利與義務','基本權總論／各論／人民之義務'],['權力分立','總論／水平：分權制衡／垂直：地方自治'],['基本國策','國家的政策方向']],stage>=2?stage-2:-1)+`<p class="diagram-caption">國家組織 → 從權力分立理解</p>`;
 if(type==='reading')return cards([['條文','讀文字與規範'],['學理、憲法解釋','理解原則與整體關係']])+`<div class="diagram-pill">學習體系 ≠ 條文目錄</div><p class="diagram-caption">例如：比例原則、審查密度</p>`;
 if(type==='change')return `<div class="change-paths">${[['01','憲政慣例','符合條件的實踐，補充憲法'],['02','憲法解釋','理解規範的意義與適用'],['03','憲法修改','依特別程序變動規範']].map(x=>`<div><b>${x[0]}</b><span><strong>${x[1]}</strong><small>${x[2]}</small></span></div>`).join('')}</div>`;
 if(type==='custom')return cards([['反覆發生','不是一次先例'],['歷時長久','長期踐行'],['確信有拘束力','不只是做習慣'],['補充性質','不能以慣例牴觸成文憲法']])+`<p class="diagram-caption">${stage===2?'副總統兼院長：不構成所稱慣例':'釋字第419號'}</p>`;
 if(type==='interpret')return stage===2?`<div class="book-story">${icon('book')}<strong>財產權的保障</strong><div class="flow-arrow">↓ 從保障目的理解</div>${cards([['有體財產','看得見、摸得到'],['無體財產','例如：著作權']])}</div>`:cards(stage>=3?[['憲法統一性','顧及整體'],['最大效力','使規範發揮效力'],['和諧解釋','調和憲法價值'],['合憲性解釋','有文義與立法意旨的界限']]:[['文義','先看文字'],['體系','看條文間的關聯'],['目的','看規定的目的'],['歷史、比較','形成背景與其他制度']],stage>=3?stage-3:-1);
 if(type==='amendment')return stage===1?`<div class="thresholds">${cards([['提議','全體立委 ¼'],['出席','全體立委 ¾'],['決議','出席委員 ¾']])}</div>`:stage===2?`<div class="amend-flow"><span>公告半年 → 人民複決</span></div><div class="diagram-pill">有效同意票 ＞ 自由地區選舉人總額 ½</div><p class="diagram-caption">分母是選舉人總額，不是投票人數</p>`:cards([['直接修改','改動原條文'],['增修條文','另外增列修改規範；我國採此方式']]);
 if(type==='limits')return cards([['想一想','修憲改為世襲帝制？'],['學說爭論','修憲有無實質界限'],['釋字第499號','肯認基本原則的界限'],['基本原則','民主共和、國民主權、人民權利、權力分立']]);
 return '';
}
function exerciseState(){const n=current();if(!n||n.kind!=='activity')return null;const a=ACTIVITIES[n.activity];const e=session.exercise;if(!e||e.node!==n.id||!Number.isInteger(e.step)||e.step<0||e.step>=a.steps.length)session.exercise={node:n.id,step:0,selected:[],feedback:false,correct:false};const state=session.exercise,s=a.steps[state.step];if(s.input==='numbers'&&!Array.isArray(state.numbers))state.numbers=s.start?[...s.start]:s.fields.map(()=>0);return state}
function exerciseStep(){const e=exerciseState();return ACTIVITIES[current().activity].steps[e.step]}
function exerciseText(){const e=exerciseState(),s=exerciseStep();return e.feedback?activityFeedback(current().activity,e.step,session.route,e.correct):s.prompt}
function exercisePanel(){const e=exerciseState(),a=ACTIVITIES[current().activity],s=exerciseStep();let work='';
 if(s.input==='numbers')work=`<div class="number-work">${s.fields.map((label,i)=>`<div class="number-field"><label for="number-${i}">${esc(label)}</label><input id="number-${i}" data-number="${i}" type="number" inputmode="numeric" min="0" max="100" step="1" value="${e.numbers[i]}" ${e.feedback?'disabled':''}><input id="range-${i}" data-number="${i}" type="range" min="0" max="100" step="1" value="${e.numbers[i]}" aria-label="調整${esc(label)}" ${e.feedback?'disabled':''}></div>`).join('')}</div>`;
 else work=`${s.input==='sequence'?`<div class="sequence-slots" aria-label="你排的順序">${s.items.map((_,i)=>`<span>${i+1} ${e.selected[i]===undefined?'待放入':esc(s.items[e.selected[i]].split('：')[0])}</span>`).join('')}</div>`:''}<div class="exercise-cards" aria-label="${s.input==='sequence'?'依順序點選卡片，再點可撤回':s.correct.length>1?'選取所有符合的卡片':'選一張卡片'}">${s.items.map((x,i)=>`<div class="evidence-row"><button class="exercise-card ${e.selected.includes(i)?'selected':''} ${e.feedback&&e.correct&&e.selected.includes(i)?'confirmed':''}" data-card="${i}" aria-pressed="${e.selected.includes(i)}" ${e.feedback?'disabled':''}><span>${e.selected.includes(i)?s.input==='sequence'?e.selected.indexOf(i)+1:'✓':String(i+1).padStart(2,'0')}</span>${esc(x)}</button>${s.evidence?`<button class="peek-btn" data-peek="${i}" aria-expanded="${e.peek===i}" aria-label="查看${esc(x)}的資料">資料</button>`:''}</div>`).join('')}</div>${s.evidence&&e.peek!==undefined?`<p class="evidence-detail">${esc(s.evidence[e.peek])}</p>`:''}`;
 const ready=s.input==='numbers'||(s.input==='sequence'?e.selected.length===s.items.length:e.selected.length>0);const hint=s.input==='numbers'?'可拖動或直接填數字':s.input==='sequence'?'依序點選；再點可撤回':s.evidence?'點「資料」查看內容':s.correct.length>1?'可複選':'選一張卡片';
 return `<div class="lesson-panel exercise-panel exercise-${s.input||a.mode}"><div class="lesson-top"><h2>${esc(a.title)}</h2><span class="exercise-count">${e.step+1}／${a.steps.length}</span></div>${s.caption?`<p class="exercise-caption">${esc(s.caption)}</p>`:''}${work}<div class="exercise-bottom"><span>${e.feedback?(e.correct?'已整理好':'再看看理由'):hint}</span>${!e.feedback?`<button class="exercise-submit" data-action="exercise-check" ${ready?'':'disabled'}>${s.input==='numbers'?'算好了':s.input==='sequence'?'排好了':'給'+esc(CAST[session.route].name)+'看'}</button>`:''}</div></div>`}
function exerciseFooter(){const e=exerciseState(),s=exerciseStep();return e.feedback?`<button class="next-btn" data-action="exercise-next">${e.correct?'繼續 ▸':'再想一次'}</button>`:`<span class="muted">${s.input==='numbers'?'調好數字，再確認':s.input==='sequence'?'排好順序，再確認':'選卡片，再給我看'}</span>`}
function exerciseSelect(i){if(mode!=='game'||modal.open||current()?.kind!=='activity')return;const e=exerciseState(),s=exerciseStep();if(e.feedback||s.input==='numbers'||!Number.isInteger(i)||i<0||i>=s.items.length)return;const selected=e.selected.includes(i);e.selected=s.input==='sequence'||s.correct.length>1?(selected?e.selected.filter(x=>x!==i):[...e.selected,i]):selected?[]:[i];clickSound();renderNode()}
function exercisePeek(i){if(mode!=='game'||modal.open||current()?.kind!=='activity')return;const s=exerciseStep();if(!s.evidence?.[i])return;const e=exerciseState();e.peek=e.peek===i?undefined:i;renderNode()}
function exerciseNumber(i,value){if(mode!=='game'||modal.open||current()?.kind!=='activity')return;const e=exerciseState(),s=exerciseStep();if(e.feedback||s.input!=='numbers'||!Number.isInteger(i)||i<0||i>=s.fields.length)return;const n=Number(value);e.numbers[i]=value===''?'':Number.isFinite(n)?Math.max(0,Math.min(100,Math.trunc(n))):'';$('#number-'+i).value=e.numbers[i];$('#range-'+i).value=e.numbers[i]||0;save()}
function exerciseCheck(){if(mode!=='game'||modal.open||current()?.kind!=='activity')return;const e=exerciseState(),s=exerciseStep();if(e.feedback)return;if(s.input==='numbers'){if(e.numbers.some(n=>n===''||!Number.isInteger(n))){toast('先把每一格的人數填好。');return}e.correct=s.answer.every((x,i)=>e.numbers[i]===x)}else if(s.input==='sequence'){if(e.selected.length!==s.items.length)return;e.correct=s.answer.every((x,i)=>e.selected[i]===x)}else{if(!e.selected.length)return;e.correct=e.selected.length===s.correct.length&&s.correct.every(x=>e.selected.includes(x))}e.feedback=true;const answer=s.input==='numbers'?s.fields.map((label,i)=>label+'：'+e.numbers[i]).join('、'):e.selected.map(i=>s.items[i]).join(s.input==='sequence'?' → ':'、');session.history.push({id:'exercise-'+current().id+'-'+e.step,who:session.name,text:answer});session.history.push({id:'feedback-'+current().id+'-'+e.step,who:CAST[session.route].name,text:exerciseText()});renderNode()}
function exerciseContinue(){if(current()?.kind!=='activity')return;const e=exerciseState();if(!e.feedback)return;if(!e.correct){e.feedback=false;e.selected=[];renderNode();return}if(e.step+1<ACTIVITIES[current().activity].steps.length){e.step++;e.selected=[];e.feedback=false;e.correct=false;delete e.numbers;delete e.peek}else{session.index=current().next;delete session.exercise}renderNode()}
function source(){const n=current();if(!n?.lesson)return;const note=NOTES[n.lesson-1];openModal('這一課的原書出處',`<div class="note-copy"><p><strong>《憲法體系二版》${note.source}</strong></p><p>依上傳書稿第一章的節次、子題與章末練習順序改編。國王、著作權及兼任爭議等教學例子取自原書；人物互動、分類卡與假設人數為遊戲改寫。</p>${note.body}</div>`)}
function openModal(title,html){finishTyping();$('#modal-title').textContent=title;$('#modal-content').innerHTML=html;if(!modal.open)modal.showModal()}
function closeModal(){modal.close()}
function notes(tab){const available=[...new Set([...store.notes,...JOURNAL.filter(j=>store.journal.includes(j.key)).map(j=>j.lesson)])].sort();if(tab===undefined)tab=current()?.lesson&&available.includes(current().lesson)?current().lesson-1:available.length?available.at(-1)-1:-1;const tabs=`<div class="modal-tabs">${NOTES.map((n,i)=>`<button ${!available.includes(i+1)?'disabled':''} data-note="${i}" class="${tab===i?'active':''}">${i+1} ${n.title}</button>`).join('')}<button data-note="course" class="${tab==='course'?'active':''}">課程目次</button></div>`;let content='';if(tab==='course'){content=`<div class="note-copy"><p>遊戲第一章對應《憲法體系二版》第一章〈總論〉，依序讀完三節已寫成的內容與章末練習：憲法的基本概念、憲法的規範體系、憲法的變遷與成長。三課依原書順序：</p>${CHAPTER_OUTLINE.map(([title,detail])=>`<div class="note-course"><div><strong>${esc(title)}</strong><p>${esc(detail)}</p></div></div>`).join('')}<p class="muted">每章對應書中一章；人物故事與練習穿插其中。釋字387號在書稿僅有未完成開頭，未自行補寫。</p></div>`}else if(tab>=0&&available.includes(tab+1)){const n=NOTES[tab];if(!store.notes.includes(tab+1)){content=`<div class="note-title">${n.title}</div><div class="note-copy">${JOURNAL.filter(j=>j.lesson===tab+1&&store.journal.includes(j.key)).map(j=>`<h3>${esc(j.title)}</h3><p>${esc(j.body)}</p>`).join('')}<p class="muted">隨著今天讀到的內容，筆記會繼續補上。</p></div>`}else content=`<div class="note-title">${n.title}</div><div class="teaching" style="min-height:220px">${diagram(n.diagram,n.stage)}</div><div class="note-copy"><p class="source-caption">原書：${n.source}</p>${n.body}</div>`}else content='<p>開始學習後，這裡會逐段留下你的筆記。</p><p class="muted">先挑一位同伴，從第一頁開始。</p>';openModal('憲法筆記',tabs+content)}
function history(){if(!session)return;openModal('剛才說到哪裡',session.history.map(l=>`<div class="history-line"><strong>${esc(l.who||'放課後')}</strong><p>${esc(l.text)}</p></div>`).join(''));setTimeout(()=>modal.scrollTop=modal.scrollHeight,0)}
function gallery(route){if(route&&store.gallery.includes(route)){const c=CAST[route];openModal(c.end,`<img class="gallery-large" src="${c.cg}" alt="${c.end}"><p style="margin-top:15px">${c.ending}</p><button class="secondary" data-action="gallery" style="margin-top:18px">回相簿</button>`);return}openModal('回憶相簿',`<div class="gallery-grid">${Object.entries(CAST).map(([r,c])=>`<button class="gallery-item" ${store.gallery.includes(r)?`data-gallery="${r}"`:'disabled'}>${store.gallery.includes(r)?`<img src="${c.cg}" alt="${c.end}">`:'<div class="gallery-empty">尚未相遇</div>'}<span>${c.name}<br>${store.gallery.includes(r)?c.end:'完成這段故事後收藏'}</span></button>`).join('')}</div>`)}
function settings(){openModal('設定',`<div class="settings-row"><label for="music-volume">配樂 <span id="music-number">${Math.round(store.settings.music*100)}%</span></label><input id="music-volume" data-setting="music" type="range" min="0" max="100" value="${store.settings.music*100}"></div><div class="settings-row"><label for="sfx-volume">音效 <span id="sfx-number">${Math.round(store.settings.sfx*100)}%</span></label><input id="sfx-volume" data-setting="sfx" type="range" min="0" max="100" value="${store.settings.sfx*100}"></div><div class="settings-row"><label for="text-speed">對話顯示</label><select id="text-speed" style="font:inherit;padding:8px;border:1px solid #bcd0d3;border-radius:6px;background:white">${[[0,'立即顯示'],[18,'快速'],[28,'適中'],[45,'慢慢讀']].map(([v,l])=>`<option value="${v}" ${store.settings.speed===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="settings-actions"><button class="secondary" data-action="mute">${store.settings.mute?'開啟聲音':'全部靜音'}</button><button class="secondary" data-action="gallery">回憶相簿</button><button class="secondary" data-action="credits">關於本作</button></div>${audioError?'<p class="audio-unavailable">配樂暫未播放。按「開啟聲音」可重試。</p>':''}<p class="settings-caption">點一下對話可立即顯示全文，再點一下前進。也可用空白鍵或 Enter；選項可按數字鍵。進度保存在目前裝置的瀏覽器。</p>${!storageOK?'<p>瀏覽器目前無法保存進度，請確認未封鎖本機儲存。</p>':''}`)}
function credits(){openModal('關於憲法放課後',`<div class="note-copy"><p><strong>第一章　靠窗的位置</strong></p><p>依作者提供的《憲法體系二版》改編。角色、晴川大學與故事均為虛構，人物皆為成年大學生；校狗與校貓為擬人化角色。</p><p>本章學習：憲法的基本概念、憲法的規範體系、憲法的變遷與成長（慣例、解釋、修改）。法源核對日期：2026年9月12日。</p><p><a href="https://www.president.gov.tw/Page/94" target="_blank" rel="noopener">憲法本文</a> · <a href="https://www.president.gov.tw/Page/95" target="_blank" rel="noopener">憲法增修條文</a></p><p>本章沒有涵蓋完整憲法課程，也不表示原書已全面更新。具體案件仍須查閱適用法規與裁判。</p><p>美術：依角色設定生成的原創插畫。配樂：為本作編寫並合成的六段器樂曲，無引用商業遊戲原聲帶或外部錄音。</p><p>支援手機與電腦。進度與偏好僅儲存在目前瀏覽器，不會跨裝置同步。</p></div>`)}
function dispatch(action){switch(action){case 'exercise-check':exerciseCheck();break;case 'exercise-next':exerciseContinue();break;case 'choose':if(modal.open)closeModal();choose();break;case 'resume':resume();break;case 'home':if(session)save();if(modal.open)closeModal();title();break;case 'next':next();break;case 'notes':notes();break;case 'source':source();break;case 'diagram':{const n=current();if(n?.diagram)openModal(diagramTitle(n.diagram),`<div class="teaching full-diagram">${diagram(n.diagram,n.stage)}</div>`);break;}case 'studyart':{const n=current();if(n?.study)openModal(CAST[session.route].name+'・一起讀書',`<img class="gallery-large" src="${studyImage(n.study)}" alt="上課事件插畫">`);break;}case 'history':history();break;case 'settings':settings();break;case 'gallery':gallery();break;case 'credits':credits();break;case 'mute':activate();store.settings.mute=!store.settings.mute;persist();if(!store.settings.mute){const track=currentTrack||'campus';if(audioError){currentTrack='';playTrack(track)}else updateVolume()}else updateVolume();settings();break;case 'viewcg':clean=!clean;$('.scene').classList.toggle('cg-clean',clean);$('.cg-view').textContent=clean?'回到對話':'欣賞圖片';break}}
let readingGesture=null;
document.addEventListener('pointerdown',e=>{readingGesture=e.target.closest('.dialogue-text')?{x:e.clientX,y:e.clientY,moved:false}:null});
document.addEventListener('pointermove',e=>{if(readingGesture&&Math.hypot(e.clientX-readingGesture.x,e.clientY-readingGesture.y)>8)readingGesture.moved=true});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b){if(b.disabled)return;if(b.dataset.action)dispatch(b.dataset.action);else if(b.dataset.peek!==undefined)exercisePeek(Number(b.dataset.peek));else if(b.dataset.card!==undefined)exerciseSelect(Number(b.dataset.card));else if(b.dataset.route)newGame(b.dataset.route);else if(b.dataset.option!==undefined)option(Number(b.dataset.option));else if(b.dataset.note!==undefined)notes(b.dataset.note==='course'?'course':Number(b.dataset.note));else if(b.dataset.gallery)gallery(b.dataset.gallery);return}if(e.target.closest('.dialogue')&&!modal.open&&!readingGesture?.moved)next()});
$('#close-modal').addEventListener('click',closeModal);
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
document.addEventListener('input',e=>{if(e.target.dataset.number!==undefined){exerciseNumber(Number(e.target.dataset.number),e.target.value);return}if(e.target.dataset.setting){const k=e.target.dataset.setting;store.settings[k]=Number(e.target.value)/100;$('#'+k+'-number').textContent=e.target.value+'%';updateVolume();persist()}});
document.addEventListener('change',e=>{if(e.target.id==='text-speed'){store.settings.speed=Number(e.target.value);persist()}});
document.addEventListener('keydown',e=>{if(modal.open||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement?.tagName))return;if(mode==='game'&&[' ','Enter'].includes(e.key)){e.preventDefault();next()}else if(mode==='game'&&/^[1-3]$/.test(e.key)){let i=Number(e.key)-1;if(current()?.kind==='activity'){e.preventDefault();exerciseSelect(i)}else if(current()?.options?.[i]){e.preventDefault();option(i)}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(deck)deck.pause();save()}else if(unlockAudio&&deck)deck.play().catch(()=>{})});
window.addEventListener('pagehide',save);
const api={read(){const n=current();return {screen:mode,route:session?.route||null,step:session?.index??null,text:n?.kind==='activity'?exerciseText():n?interpolate(n.text):'',activity:n?.kind==='activity'?{key:n.activity,step:exerciseState().step,selected:[...exerciseState().selected],feedback:exerciseState().feedback,correct:exerciseState().correct,items:exerciseStep().items,input:exerciseStep().input||'cards',numbers:exerciseState().numbers?[...exerciseState().numbers]:null,peek:exerciseState().peek}:null,choices:n?.options?.map((o,i)=>({index:i,text:o.label}))||[],notes:[...store.notes],journal:[...store.journal],gallery:[...store.gallery]}}};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_constitution_story',title:'讀取目前故事',description:'取得目前憲法遊戲的對話、可選回應及學習進度。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>api.read()})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'choose_constitution_reply',title:'選擇故事回應',description:'以目前顯示的零起算選項編號選擇回應，推進故事；只在選項畫面有效。',inputSchema:{type:'object',properties:{index:{type:'integer',minimum:0,maximum:2}},required:['index'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(modal.open)throw Error('請先關閉視窗');if(!input||!Number.isInteger(input.index))throw Error('需要整數選項');option(input.index);return api.read()}})).catch(()=>{})}catch(e){}}
title();
})();
